snow_tricks_trick:
    resource: "@SnowTricksTrickBundle/Resources/config/routing.yml"
    prefix:   /

snow_tricks_app:
    resource: "@SnowTricksAppBundle/Resources/config/routing.yml"
    prefix:   /

snow_tricks_user:
    resource: '@SnowTricksUserBundle/Resources/config/routing.yml'
    prefix:   /

login:
    path: /login
    defaults:
        _controller: SnowTricksUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout