# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SnowTricks\AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    SnowTricks\AppBundle\Entity\User
                property: username

    access_control:
            - { path: ^/trick/add, role: ROLE_USER }
            - { path: ^/trick/edit, role: ROLE_USER }
            - { path: ^/comment/add, role: ROLE_USER }
            - { path: ^/dashboard, role: ROLE_USER }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change: true
            pattern:   ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
