# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SnowTricks\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      # … vous pouvez supprimer le fournisseur « in_memory »
      # Et voici notre nouveau fournisseur :
        main:
            entity:
                class:    SnowTricks\UserBundle\Entity\User
                property: username

    access_control:
            #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
