<?php

namespace App\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use App\Entity\Comment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Comment::class);
    }

    const MAX_COMMENTS = 10;

    public function findCommentsByTrick($id)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment')
            ->orderBy('comment.id', 'DESC')
            ->andWhere('comment.trick = :id')
            ->setMaxResults($this::MAX_COMMENTS)
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function findOtherComments($id, $lastComment)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment')
            ->orderBy('comment.id', 'DESC')
            ->andWhere('comment.id < :lastComment')
            ->andWhere('comment.trick = :id')
            ->setMaxResults($this::MAX_COMMENTS)
            ->setParameter('lastComment', $lastComment)
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
