<?php

namespace App\Repository;

use App\Entity\Trick;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;


/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Trick::class);
    }

    const MAX_TRICKS = 15;

    public function listTricks()
    {
        return $this->createQueryBuilder('trick')
            ->select('trick')
            ->orderBy('trick.id', 'DESC')
            ->setMaxResults($this::MAX_TRICKS)
            ->getQuery()
            ->getResult();
    }


    public function findOtherTricks($id)
    {
        return $this->createQueryBuilder('trick')
            ->select('trick')
            ->orderBy('trick.id', 'DESC')
            ->andWhere('trick.id < :lastTrick')
            ->setMaxResults($this::MAX_TRICKS)
            ->setParameter('lastTrick', $id)
            ->getQuery()
            ->getResult();
    }

}
