snow_tricks_comment_add:
    path:     /comment/add/{id}
    defaults: { _controller: SnowTricksCommentBundle:Comment:add }
    requirements:
            id: '\d+'
snow_tricks_comment_list_comment_ajax:
    path:     /comment/trick/{id}/{lastComment}
    defaults: { _controller: SnowTricksCommentBundle:Comment:listCommentByTrickAndAjax }
    requirements:
            id: '\d+'
            lastComment: '\d+|null'