snow_tricks_user_registration:
    path:     /registration
    defaults: { _controller: SnowTricksUserBundle:Security:register }
snow_tricks_user_tokenVerification:
    path:     /token/{token}
    defaults: { _controller: SnowTricksUserBundle:Security:tokenVerification }