<?php

namespace SnowTricks\AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCommentsByTrick($id)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment')
            ->orderBy('comment.id', 'DESC')
            ->andWhere('comment.trick = :id')
            ->setMaxResults(10)
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function findOtherComments($id, $lastComment)
    {
        return $this->createQueryBuilder('comment')
            ->select('comment')
            ->orderBy('comment.id', 'DESC')
            ->andWhere('comment.id < :lastComment')
            ->andWhere('comment.trick = :id')
            ->setMaxResults(10)
            ->setParameter('lastComment', $lastComment)
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
